version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: upload
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: serverteste
      POSTGRES_DB: upload
    ports:
      - '5498:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    restart: always

volumes:
  postgres_data:

networks:
  postgres_network:
