version: '3.9'

services:
  app:
    restart: always
    container_name: nestjs_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - default

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5498:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
    restart: always

volumes:
  postgres_data:
